.TH MKVTOOL 1
.SH NAME
mkvtool \- Automatic fonts subset tool.
.SH
This man page is out-of-date. Please check README.md file from https://github.com/MkvAutoSubset/MkvAutoSubset .
.SH 
.SH SYNOPSIS
.B mkvtool
.RB [ input_options ]
.RB [ input_url ]
.RB [ output_options ]
.RB [ output_url ]
.SH DESCRIPTION
mkvtool is an automatic fonts subset tool. It can help you extract certain character(letter) fonts in special effect subtitles(.ass or .ssa format) from videos, and re-package mkv files in order to decrease file size.
.SH OPTIONS
( out-of-date )
.SH EXAMPLES
You can find examples in README.md.
.SH BUGS
UNKNOWN
.SH AUTHOR
Written by anonym.
.SH COPYRIGHT
Under GNU GENERAL PUBLIC LICENSE Version 3. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law. 
