.TH MKVTOOL 1
.SH NAME
mkvtool \- Automatic fonts subset tool.
.SH SYNOPSIS
.B mkvtool
.RB [ input_options ]
.RB [ input_url ]
.RB [ output_options ]
.RB [ output_url ]
.SH DESCRIPTION
mkvtool is an automatic fonts subset tool. It can help you extract certain character(letter) fonts in special effect subtitles(.ass or .ssa format) from videos, and re-package mkv files in order to decrease file size.
.SH OPTIONS
.TP
.B \-a [value]
ASS files. (multiple & join ass mode)
.TP
.B \-af [string]
ASS fonts folder. (ass mode only)
.TP
.B \-ans
ASS output not to the new "subsetted" folder. (ass mode only)
.TP
.B \-ao [string]
ASS output folder. (ass mode only)
.TP
.B \-c
Create mode.
.TP
.B \-clean
Clean original file subtitles and fonts. (create mode only)
.TP
.B \-d
Dump mode.
.TP
.B \-data [string]
Subtitles & Fonts folder (dump & make mode only) (default "data")
.TP
.B \-dist [string]
Results output folder (make mode only) (default "dist")
.TP
.B \-f [string]
MKV file. (join single mode)
.TP
.B \-log [string]
Log file path
.TP
.B \-m
Make mode.
.TP
.B \-n
Not do ass font subset. (dump mode only)
.TP
.B \-q
Query mode.
.TP
.B \-s [string]
Source folder.
.TP
.B \-sl [string]
Subtitle language. (create & make mode only) (default "chi")
.TP
.B \-st [string]
Subtitle title. (create & make mode only)
.TP
.B \-v
Show app info.
.SH EXAMPLES
You can find examples in README.md.
.SH BUGS
UNKNOWN
.SH AUTHOR
Written by anonym.
.SH COPYRIGHT
Under GNU GENERAL PUBLIC LICENSE Version 3. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law. 
